@startuml
class Key {
    + PublicField : int = 0
    + {static} PublicFieldStatic : int = 0
    - _privateField : int = 0
    - {static} _privateFieldStatic : int = 0
    + PublicMethod() : int
    + {static} PublicMethodStatic() : int
    - PrivateMethod() : int
    - {static} PrivateMethodStatic() : int
}
@enduml
