@startuml
class Concept2 {
    - _concept2 : int
    + Concept2Function() : int
}
class Concept1 {
    - _concept1 : int
    + Concept1Function() : int
}
class ExtractClassAfter {
    - <<readonly>> _concept1 : Concept1
    - <<readonly>> _concept2 : Concept2
}
@enduml
