@startuml
!include .\\Encapsulate\EncapsulateField.p.\
!include .\\Keys\FullKey.p.\
!include .\\Keys\Key.p.\
!include .\\Extract\After\ExtractClass.p.\
!include .\\Extract\After\ExtractField.p.\
!include .\\Extract\After\ExtractFieldStatic.p.\
!include .\\Extract\After\ExtractInterface.p.\
!include .\\Extract\After\ExtractSuperclass.p.\
!include .\\Extract\Before\ExtractClassBefore.p.\
!include .\\Extract\Before\ExtractFieldBefore.p.\
!include .\\Extract\Before\ExtractFieldStaticBefore.p.\
!include .\\Extract\Before\ExtractInterfaceBefore.p.\
!include .\\Extract\Before\ExtractSuperclassBefore.p.\
!include .\\obj\Debug\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.p.\
!include .\\obj\Debug\net5.0\RefactoringSamples.AssemblyInfo.p.\
!include .\\obj\Release\net5.0\.NETCoreApp,Version=v5.0.AssemblyAttributes.p.\
!include .\\obj\Release\net5.0\RefactoringSamples.AssemblyInfo.p.\
@enduml
